version: "3"
services:
  terraform:
    image: hashicorp/terraform:light
    working_dir: /terraform
    volumes:
      - ./:/terraform
    env_file: ./.env
  terraform-production:
    image: hashicorp/terraform:light
    working_dir: /terraform/environments/production
    volumes:
      - ./:/terraform
    env_file: ./.env
